#服务端口
server.port=8082
#服务名
spring.application.name=guliedu-edu

#环境设置：dev、test、prod
spring.profiles.active=dev

#mysql数据库连接
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/guliedu_edu
spring.datasource.username=root
spring.datasource.password=root

#如果不使用默认的数据源 （com.zaxxer.hikari.HikariDataSource）
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

#mybatis日志
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#逻辑删除
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

#配置mapper xml文件的路径
mybatis-plus.mapper-locations=classpath:com/atguigu/gulixueyuan/edu/mapper/xml/*.xml